version: '3.8'

services:
  # PostgreSQL Database - Using existing image if available
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: agent_monitor
      POSTGRES_USER: agent_monitor  
      POSTGRES_PASSWORD: agent_monitor_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - agent-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent_monitor -d agent_monitor"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Monitor Dashboard
  monitor-dashboard:
    image: agent_monitor-monitor:latest
    command: python main_production_server.py
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://agent_monitor:agent_monitor_password@postgres:5432/agent_monitor
    volumes:
      - agent_data:/app/data
    networks:
      - agent-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/agents/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Agent 1 - LLM Agent
  agent-1:
    image: agent_monitor-test-agent:latest
    command: python simple_container_agent.py
    restart: unless-stopped
    environment:
      - AGENT_NAME=🤖 LLM Agent 1
      - AGENT_TYPE=LLM_AGENT
      - WORKLOAD_TYPE=llm
      - AGENT_ENVIRONMENT=DOCKER
      - MONITOR_URL=http://monitor-dashboard:8000
      - PYTHONPATH=/app
    networks:
      - agent-network
    depends_on:
      monitor-dashboard:
        condition: service_healthy

  # Agent 2 - API Agent  
  agent-2:
    image: agent_monitor-test-agent:latest
    command: python simple_container_agent.py
    restart: unless-stopped
    environment:
      - AGENT_NAME=🔌 API Agent
      - AGENT_TYPE=API_AGENT
      - WORKLOAD_TYPE=api
      - AGENT_ENVIRONMENT=DOCKER
      - MONITOR_URL=http://monitor-dashboard:8000
      - PYTHONPATH=/app
    networks:
      - agent-network
    depends_on:
      monitor-dashboard:
        condition: service_healthy

  # Agent 3 - Data Agent
  agent-3:
    image: agent_monitor-test-agent:latest
    command: python simple_container_agent.py
    restart: unless-stopped
    environment:
      - AGENT_NAME=📊 Data Agent
      - AGENT_TYPE=DATA_AGENT
      - WORKLOAD_TYPE=data
      - AGENT_ENVIRONMENT=DOCKER
      - MONITOR_URL=http://monitor-dashboard:8000
      - PYTHONPATH=/app
    networks:
      - agent-network
    depends_on:
      monitor-dashboard:
        condition: service_healthy

  # Agent 4 - ML Agent
  agent-4:
    image: agent_monitor-test-agent:latest
    command: python simple_container_agent.py
    restart: unless-stopped
    environment:
      - AGENT_NAME=🧠 ML Agent
      - AGENT_TYPE=CUSTOM
      - WORKLOAD_TYPE=ml
      - AGENT_ENVIRONMENT=DOCKER
      - MONITOR_URL=http://monitor-dashboard:8000
      - PYTHONPATH=/app
    networks:
      - agent-network
    depends_on:
      monitor-dashboard:
        condition: service_healthy

  # Agent 5 - Monitor Agent
  agent-5:
    image: agent_monitor-test-agent:latest
    command: python simple_container_agent.py
    restart: unless-stopped
    environment:
      - AGENT_NAME=📡 Monitor Agent
      - AGENT_TYPE=MONITOR_AGENT
      - WORKLOAD_TYPE=standard
      - AGENT_ENVIRONMENT=DOCKER
      - MONITOR_URL=http://monitor-dashboard:8000
      - PYTHONPATH=/app
    networks:
      - agent-network
    depends_on:
      monitor-dashboard:
        condition: service_healthy

networks:
  agent-network:
    driver: bridge

volumes:
  agent_data:
    driver: local
  postgres_data:
    driver: local