version: '3.8'

services:
  pulseguard-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: pulseguard-dashboard
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - pulseguard-network

networks:
  pulseguard-network:
    driver: bridge